app/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView
from django.contrib import admin
from tasks.views import HomeView, UserUpdateView, UserProfileUpdateView, \
    AddressFileView, AddressFileDetailView, TaskListView, RewardListView, \
    TaskCreateView, TaskUpdateView, TaskDetailView, TaskDeleteView, TaskSubscribeView, \
    RewardCreateView, RewardDetailView, RewardUpdateView, RewardDeleteView
from tasks.ajax import post_task, save_answer, get_address, get_geocoders_results, get_geocoders_output
from map.views import MapTaskView

urlpatterns = patterns('',
	(r'^accounts/', include('allauth.urls')),
    url(r'^choose-language$', 'django.views.i18n.set_language', name='set_language'),
    #App Home
    url(r'^$', 'app.views.home', name='home'),
    #CrowdGeocode Map
    # url(r'^map/$', 'map.views.map', name='map'),
    url(r'^map/task/(?P<pk>\d+)/$', MapTaskView.as_view(), name='map-task'),
    #Home/Profile Site
    url(r'^my-profile/$', HomeView.as_view(), name='my-profile'),
    url(r'^my_profile/$', 'tasks.views.my_profile', name='my_profile'),
    #Edit user profile views
    url(r'^my-profile/user/edit/',  UserUpdateView.as_view(), name='user-edit'),
    url(r'^my-profile/description/edit/',  UserProfileUpdateView.as_view(), name='profile-edit'),

    #List with all tasks
    url(r'^tasks/$', TaskListView.as_view(), name='all_tasks'),
    #Task creation
    url(r'^task-new/$', TaskCreateView.as_view(), name='task-new'),
    #Detail of 1 task
    url(r'^task-detail/(?P<pk>\d+)/$', TaskDetailView.as_view(), name='task-detail'),
    #Task edition
    url(r'^task-edit/(?P<pk>\d+)/$', TaskUpdateView.as_view(), name='task-edit'),
    #Task delete
    url(r'^task-delete/(?P<pk>\d+)/$', TaskDeleteView.as_view(), name='task-delete'),
    #Task subscribe modal confirmation message
    url(r'^task-subscribe/$', TaskSubscribeView.as_view(), name='task-subscribe'),
    #List with all rewards
    url(r'^rewards/$', RewardListView.as_view(), name='all_rewards'),
    #Reward creation
    url(r'^reward-new/$', RewardCreateView.as_view(), name='reward-new'),
    #Detail of 1 reward
    url(r'^reward-detail/(?P<pk>\d+)/$', RewardDetailView.as_view(), name='reward-detail'),
    #Reward edition
    url(r'^reward-edit/(?P<pk>\d+)/$', RewardUpdateView.as_view(), name='reward-edit'),
    #Reward delete
    url(r'^reward-delete/(?P<pk>\d+)/$', RewardDeleteView.as_view(), name='reward-delete'),

    #Other URLs
    url(r'^access_denied/$', TemplateView.as_view(template_name='access_denied.html'), name='access_denied'),
    #Contact
    url(r'^contact/$', 'contact.views.contacto', name='contact'),
    
    #Upload file
    url(r'^upload-file/$', AddressFileView.as_view(), name='upload-file'),
    #View file
    url(r'^file/(?P<pk>\d+)/$', AddressFileDetailView.as_view(),
        name='file'),
    
    #AJAX PROCESSING#
    url(r'^get-address/$', 'tasks.ajax.get_address', name='get-address'),
    url(r'^geocode/$', 'tasks.ajax.get_geocoders_output', name='geocode'),
    #url(r'^get-geocoders/$', 'tasks.ajax.get_geocoders_results', name='get-geocoders'),
    #POST to subscribe to a task
    url(r'^post-task/$', 'tasks.ajax.post_task', name='post-task'),
    #POST to save one task answers
    url(r'^save-answer/$', 'tasks.ajax.save_answer', name='save-answer'),


    url(r'^admin/', include(admin.site.urls)),
)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.conf import settings

# Create your models here.

class Contact(models.Model): 
	user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True)
	name = models.CharField(max_length=120, default='', blank=True)
	email = models.EmailField()
	subject = models.CharField(max_length=120)
	message = models.TextField()
	timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)

	def __unicode__(self):
		if self.name:
			return "%s %s" %(self.name, " sent a message!")
		else:
			return "%s %s" %(self.email, " sent a message!")

contact/forms.py
# -*- coding: utf-8 -*-
from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):
	def __init__(self, *args, **kwargs):
	    super(ContactForm, self).__init__(*args, **kwargs)
	    #Aquí puedo hacer modificaciones al modelo y la presentación
	    #del formulario
	    #self.fields['name'].required = True
	    #self.fields['name'].widget.attrs['readonly'] = True
	    #self.fields['user'].widget.attrs['disabled'] = True
	    #self.fields['user'].widget = forms.HiddenInput()
	    #self.fields['name'].initial =  'override'
	    
	class Meta:
		model = Contact
		#fields = ('email','name','subject', 'message')
		fields = '__all__'
		#exclude = ['user']
		#widgets = {'user': forms.HiddenInput()} 

contact/views.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.shortcuts import render
from django.utils.translation import ugettext_lazy as _

from django import forms
from .forms import ContactForm
# Create your views here.

def contacto(request):
	title = _('Need some help?')
	form = ContactForm(request.POST or None)
	form.fields['user'].widget.attrs['disabled'] = True
	confirm_message = None
	if request.user.is_anonymous():
		form.fields['user'].widget = forms.HiddenInput()

	if form.is_valid():
		#store in a model
		new_message = form.save(commit=False)
		#Puedo hacer cambios aquí antes de guardar
		if request.user.is_authenticated():
			user = request.user
			new_message.user = user
			new_message.save()
		else:
			user = None
			new_message.user = user
			new_message.save()
			
		title = _('Thanks')
		confirm_message = _('We have received your message, we will contact you soon!')
		form  = None

	context = {
		'title' : title,
		'form' : form,
		'confirm_message': confirm_message
			}

	template = 'contact.html'
	return render(request, template, context)

templates/access_denied.html
{% extends "account/base.html" %}

{% load i18n %}

{% block head_title %}Acceso restringido{% endblock %}

{% block content %}

<div style="text-align:center">
	<p>Usuario: {{ user.username }} ({{ user.email }})</p>

<h3>Sorry! You do not permission to edit this task...</h3>
</div>


{% endblock %}

templates/base.html
{% load i18n %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<meta charset="UTF-8" />
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <head>
        <title>{% block head_title %} {% endblock %} | Crowd-GeoCoding</title>

         <!-- Boostrap -->
         <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
         <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
        
         <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
         <!-- JQuery -->
	       <link rel="stylesheet" type="text/css" href="https://code.jquery.com/ui/1.11.4/themes/ui-lightness/jquery-ui.css"> 
<style>
      body{ 
        padding-top: 0.5%;
        padding-left: 2%;
        padding-right: 2%; 
               }
    .navbar{
        margin-bottom:10px;
    }
    .alert.alert-success {
          border: 3px solid #1E824C;
          border-radius: 5px;
          background-color: rgba(30, 130, 76, 0.4);
           }
    .alert-alert-warning {
          border: 3px solid #D35400;
          border-radius: 5px;
          background-color: rgba(211, 84, 0, 0.4); }
    .alert {
          border: 3px solid #D91E18;
          border-radius: 5px;
          background-color: rgba(217, 30, 24, 0.4); }
    .alert.alert-info {
          border: 3px solid #3498DB;
          border-radius: 5px;
          color: #fff;
          background-color: rgba(52, 152, 219, 0.4); }
    .modal-backdrop {
        z-index: -1;
      }
      .bs-header {
        color: #e3effe;
        background-color: #7A89A6;
        }
      .bs-header {
        padding: 20px 15px 30px; /* side padding builds on .container 15px, so 30px */
        font-size: 16px;
        text-align: center;
        text-shadow: 0 1px 0 rgba(0,0,0,.15);
      }
      .bs-header h1 {
        color: #fff;
      }
      .bs-header p {
        font-weight: 300;
        line-height: 1.5;
      }
      .bs-header .container {
        position: relative;
      }
      .spinner {
        position: fixed;
        top: 50%;
        left: 50%;
        margin-left: -50px; /* half width of the spinner gif */
        margin-top: -50px; /* half height of the spinner gif */
        text-align:center;
        z-index:1234;
        overflow: auto;
        width: 100px; /* width of the spinner gif */
        height: 102px; /*hight of the spinner gif +2px to fix IE8 issue */
    }
</style>
{% block head_style %}
{% endblock %}
{% include 'navbar.html' %}
</head>
<body>
    <div id="spinner_tool" class="spinner" style="display:none;">
      <i class="fa fa-cog fa-spin fa-5x"></i>
    </div>
    <div id="spinner_earth" class="spinner" style="display:none;">
          <img id="img-spinner" src="{% static 'img/earth-loader.gif' %}" alt="Loading"/>
    </div>
{% block content %} 
{% endblock %}
<hr>
<footer>
  <h6>Crowd-GeoCoding | 2020 © All rights reserved</h6>
</footer>
    <!-- JQuery --> 
    <script type='text/javascript' src='https://code.jquery.com/jquery-2.1.4.min.js'></script>
    <script type='text/javascript' src='https://code.jquery.com/ui/1.11.4/jquery-ui.min.js'></script>
    <script src="https://malsup.github.com/jquery.form.js"></script>
    <!-- Bootstrap -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block jquery %}
    {% endblock %}
 </body>
</html>

templates/contact.html
{% extends 'base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block head_title %} Contacto {% endblock %}

{% block jquery %}

<script type="text/javascript">

$(document).ready(function(){


$('#id_user').val("{{ user.id }}")
$('#id_name').val("{{ user.first_name}} {{ user.last_name}} ")
$('#id_email').val("{{ user.email }}")

});

</script>
 
{% endblock %}

{% block content %}

<div class='row'>
	<div class='col-sm-6 col-sm-offset-3 col-xs-10 col-xs-offset-1'>
		
			<h2>{{title}}</h2>
			<br>
			{% if confirm_message %}
			<p>{{confirm_message}}</p>
			{% endif %}
		
		
			{% if form %}
				<form method='POST' action=''>{% csrf_token %} 
					{{ form | crispy }}
				<input type='submit' value= "{% trans 'Send message &raquo;' %}" class='btn btn-primary' ></input>
				</form> 
			{% endif %}
		
	</div>
</div>

{% endblock %}

templates/form.html
{% extends 'base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block head_title %} {{title_action}} {% endblock %}

{% block jquery %}

 
{% endblock %}

{% block content %}

<div class='row'>
	<div id="Panel" class="col-sm-6 col-sm-offset-3 col-xs-10 col-xs-offset-1">
		<div class="panel panel-primary">
	  		<div class="panel-heading">
	    	<p class="panel-title" style="text-align:center">Username: {{ user.username }}</strong></p>
	    	
	  		</div>
		  	<div class="panel-body">		
					{% if form %}
						<form method='POST' action=''>{% csrf_token %} 
							{{ form | crispy }}
						<input type='submit' style="float:left;" value= "{% trans 'Save &raquo;' %}" class='btn btn-primary' ></input>
						</form> 
					
						<a href="{% url 'my-profile' %}" class="btn btn-default" style="float:right;">Cancel</a>
					{% endif %}
		  	</div>
		</div>
	</div>
</div>


{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block head_title %} Hi! {% endblock %}

{% block head_style %}
<style>
	.jumbotron {
	  padding: 125px 50px;

	}
	.jumbotron, .jumbotron h1 {
	  text-align: center;
	  font-size: 50px;

	}
	.char{
		padding: 100px 50px;
	}
	.char2{
		padding: 0px 85px;
	}
	img {
	  /*border: 1px solid #ddd;
	  border-radius: 4px;*/
	  width: 550px;
	}

	@media (max-width:767px) {
    img {
       width: 400px;
    }
</style>

{% endblock %}

{% block content %}
		<div class="jumbotron">
	        <h1 class="text-center">Crowd-GeoCoding</h1>
	       <div class="row">
	       	<div class="col-md-10 col-md-offset-1">
		        <p class="lead">On some occasions, the available addresses of offices, restaurants, theaters, etc. published online are incorrect or incomplete. Making it difficult to get there.
				</p>
		        <a class="btn btn-lg btn-success" href="/tasks/" role="button">Help correct them!</a>
		        <br>
		        <a class="btn btn-default btn-link" href="/accounts/signup/" role="button">Sign up to help someone!</a>
		      </div>
	        </div>
		</div>
      <div class="row char">
        <div class="col-md-6">
        	<h3>Crowd-GeoCoding...</h3>
        	<ul>
			  <li>Relies on the cognitive abilities and local knowledge of volunteers.</li>
			  <li>Enables distributed user online participation in geocoding validation tasks.</li>
			  <li>Facilitates open collaboration to analyze the geographic accuracy of different online geocoding services.</li>
			  <li>Helps participants identify and select the best service outcome or manually geocode a correct address on the map.</li>
			  <li>Allows downloading the database with the results of a task to evaluate the quality of geocoding services.</li>
			</ul>
        </div>
        <div class="col-md-5">
        	<img src="{% static 'img/task_example.png' %}">
        </div>
     </div>
     
     <div class="row char2 text-center">
        <div class="col-md-6">
        	<br>
        	<p>Crowd-Geocoding allows you to <b>create a crowdsourcing task by uploading a CSV file and generate a database with addresses or place names to validate.</b></p>
        </div>
        <div class="col-md-6">
        	<p>Within a crowdsourcing task, the address selected by a volunteer (user) is geocoded by <b>Google Maps, Bing Maps, MapQuest and OpenStreetMap (OSM) online APIs</b>. The results of the geocoders are presented on a map for the user to explore and select the best result based on their knowledge of the geographic area. <b>The volunteer can also suggest a location.</b></p>
        </div>
     </div>
{% endblock %}

templates/navbar.html
{% load i18n %}
<div class="navbar navbar-inverse">
    <div class="container">
        <div class="navbar-header">
          <a href="{% url 'home' %}" class="navbar-brand">Crowd-GeoCoding</a>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav navbar-right">
            <li>
              <a id="lan_picker">
               <form action="{% url 'set_language' %}" method="post">
                  {% csrf_token %}
                  <input name="next" type="hidden" value="{{ redirect_to }}" />
                  <select name="language">
                      {% get_language_info_list for LANGUAGES as languages %}
                      {% for language in languages %}
                          <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected="selected"{% endif %}>
                               {{ language.name_local }} ({{ language.code }})
                          </option>
                      {% endfor %}
                  </select>
                  <input type="submit" value= {% trans "Go" %} />
              </form>
              </a>
            </li>
            <li><a href="{% url 'contact' %}">{% trans "Q?" %}</a></li>
            <li><a href="{% url 'my-profile' %}">{% trans "My Profile" %}</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">{% trans "User" %}<b class="caret"></b></a>
              <ul class="dropdown-menu" style="text-align:center">
              {% if not request.user.is_authenticated %}
                <li><a href="{% url 'account_login' %}">{% trans "Log in" %}</a></li>
                <li class="divider"></li>
                <li><a href="{% url 'account_signup' %}">{% trans "Sign up" %}</a></li>
                {% else %}
                <li style="color:#0078AE;"><h6>U: {{user}}</h6></li>
                <li><a href="{% url 'account_logout' %}">{% trans "Log out" %}</a></li>
                {% endif %}
              </ul> 
            </li>
          </ul>

        </div>

    </div>      
</div>